
services:
  eureka-server:
    build: ./backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_DASHBOARD_PASSWORD: ${EUREKA_DASHBOARD_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    build: ./backend/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      GATEWAY_DASHBOARD_PASSWORD: ${GATEWAY_DASHBOARD_PASSWORD}
      GATEWAY_JWT_SECRET: ${GATEWAY_JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - eureka-server
      - redis
      - db
      - usuario
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 40

  usuario:
    build: ./backend/usuario
    container_name: usuario
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend/ecommerce-web
    container_name: ecommerce-web
    ports:
      - "4200:80"
    depends_on:
      - gateway
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data: