# ========================================
# Gateway configuration for user-service and product-service
# ========================================

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        # Rate limiter to prevent abuse
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@remoteAddressKeyResolver}"
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
        # Circuit breaker for fault tolerance
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/fallback
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:4200"
                allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
                allowed-headers: "*"
                exposed-headers: "Authorization,X-Usuario,X-Roles,X-Email,X-JWT-Id"
                allow-credentials: true
      routes:
        # =============================
        # USER SERVICE ROUTES
        # =============================
        
        # =============================
        # AUTH SERVICE ROUTES
        # =============================
        # No JWT required
        # Auth endpoints (login, register)
        # These should be public and not require JWT
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/api/auth/**
          filters:
            # Removes '/api' prefix before forwarding to usuario
            - StripPrefix=1
                   
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/api/usuarios/**
          filters:
            # Removes '/api' prefix before forwarding to usuario
            - StripPrefix=1

        # Protected access: /api/segura/usuarios/*
        # JWT required
        - id: usuario-secure
          uri: lb://usuario
          predicates:
            - Path=/api/segura/usuarios/**
          filters:
            # Removes '/api/segura' prefix before forwarding to usuario
            - StripPrefix=2

        # =============================
        # PRODUCT SERVICE ROUTES
        # =============================

        # Public access: /api/productos/*
        # No JWT required
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/productos/**
          filters:
            # Removes '/api' prefix before forwarding to product-service
            - StripPrefix=1

        # Protected access: /api/segura/productos/*
        # JWT required
        - id: product-service-secure
          uri: lb://product-service
          predicates:
            - Path=/api/segura/productos/**
          filters:
            # Removes '/api/segura' prefix before forwarding to product-service
            - StripPrefix=2


gateway:
  filter:
    # JWT secret for signing and verifying tokens
    jwt-secret: ${GATEWAY_JWT_SECRET:dev_secret}
    # Only paths starting with /api/segura/ are protected by JWT
    conditional-path: /api/segura/
    # Allowed roles for JWT authentication
    allowed-roles: ROLE_ADMIN,ROLE_USER
    # Custom claim mappings for role and email in the JWT
    role-claim: rol
    email-claim: email
    order: 100
    # Paths that are always public, even if under /api/segura/
    exempt-paths: /auth/login,/usuarios/register

  security:
    user:
      name: admin
      password: ${GATEWAY_DASHBOARD_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8080
  ssl:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always