spring:
  application:
    name: eureka-server

server:
  port: 8761
  ssl:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always